src/components/VirtualScroller.vue
window event was getting passed to updateVisibleItems(), which treated it as force = true
=> bugfix: updateVisibleItems accidentally being called with 'force'

src/components/VirtualScroller.vue
When using virtual scroller with variable height mode and two items, the
first item can become invisible. Please see fiddle:
http://jsfiddle.net/6r6eonhe/
=> Fix for invisible elements

index.js
`export default from '/file'` is invalid syntax and will not work in many parsers
=> use correct ES2015 syntax

README.md, docs-src/src/App.vue, docs-src/src/Item.vue, src/components/RecycleList.vue
**Problem**: while currently the `RecycleList` may take any array of items as a prop, using it comes at the cost of losing access to the traditional `v-for` loop, which exposes item indexes.
In some cases knowing the index of each item is required, and while a work-around would be to modify the data structure passed into `items` to include the index, a cleaner alternative is to make it available to devs as a scoped property.
The PR provides this, as I noticed it was readily available in the `view.nr` object.
=> Add index to scoped props available in RecycleList

src/mixins/scroller.js
this component cannot work well in ios device with page-mode
because of the default scroller is not pointed to window
=> The default target for IOS should be body

docs-src/src/App.vue
When i tried the demo on an iPad the scroll in `.vue-recycle-scroller` wasn't "kinetic". So I added a line of CSS to fix the demo.
=> Add styles for kinetic scrolling on touch device in docs demo

README.md
The DynamicScroller link from the "Usage" section did not properly lead to the "Dynamic Scroller" subsection.
=> docs: fix DynamicScroller anchor

README.md
The CSS file is not imported by default, so the doc should read "should be included", not "is included".
=> Fix misleading CSS file import instruction

build/rollup.config.es.js
Since `Object.assign` does not merge nested array, the `external` option in `rollup.config.es.js` does not include `vue`. Then the ES module bundle includes Vue code which seems not intended behavior.
=> chore: exclude vue for es module bundle

src/components/RecycleScroller.vue
`handleScroll` is checking for position diff `checkPositionDiff` and returning `{ continuous: false }` which causes handleScroll to recheck again and again. This way, handleScroll is allowed only once to trigger `updateVisibleItems`.
Also, question, I guess `this.$_scrollDirty` is used to prevent queuing multiple requests for animation frame. Would better option be to assign return from `requestAnimationFrame` to a variable and before it do a `cancelAnimationFrame`. That way only one, the latest request, will be triggered.
=> fix: Avoid updatingVisibleItems loop

src/components/RecycleScroller.vue
I'm still researching this. So far I've seen that `updateVisibleItems` is called multiple times on initial load which helps it to hide this issue.
When `updateVisibleItems` is called first time it has a bug. For first item it doesn't have available views in a pool, so it creates new unused view, for second item it gets view and adjust it to second item. Third item again doesn't have available view in the pool etc...
When `updateVisibleItems` is called second time everything is fine. Usually you don't see anything between calls because they are fast. In our case items render time is slow so you can clearly see this bug.
Basically this will create unused view and then assign item to it. This is probably fixing #368 
Also in the process I did small refactoring.
What do you think, am I …
=> Small refactoring and fix

docs-src/src/components/DynamicScrollerDemo.vue, src/components/RecycleScroller.vue
this is testable by setting the `.notice` class to a 500px height on the dynamic scroller demo
=> fix: Account for the height of the leading and trailing slots when calculating visible items, fix #685

src/components/RecycleScroller.vue
when we use router-view and keep alive with RecycleScroller, if we change the router, then back, we will see the scroller position will change to the top. we need to keep the position
=> fix: restore scroll in keep-alive

src/components/DynamicScroller.vue
When using DynamicScroller, the `keyField` prop was ignored because it was manually set as its default value `id` here.
=> fix: DynamicScroller should pass its own keyField prop to child RecycleScroller

src/components/DynamicScrollerItem.vue
This fixes the issue when the dynamic scroller disappears out of view and the this.$el.parentNode returns nothing causing the observer to have issues, stack trace for current issue follows
[Vue warn]: Error in beforeDestroy hook: "TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'."
```
found in
---> <DynamicScrollerItem>
<RecycleScroller>
<DynamicScroller>
<SeatSelect> at src/components/SeatSelectComponent.vue
<Event> at src/views/Event.vue
<App> at src/App.vue
<Root>
```
=> fix: issue with beforeDestroy hook

README.md, src/components/DynamicScroller.vue, src/components/RecycleScroller.vue, src/components/common.js
I would like to have the ability to author semantic list element types. For example, I want vue-virtual-scroller to support rendering its virtual list in a `ul>li` tree. This addition adds props (and docs) that support configuring the direct list and list item element types.
=> feat: adds configurable list/item tags for semantic html

src/components/DynamicScrollerItem.vue
Hello !
I just had a hard time understanding what was happening because I set badly the `key-field` prop on the DynamicScroller.
I propose this change so that the component fails faster with a clearer error, does this feel right to you ?
Thanks !
=> feat: throw error when key field does not exist in item

docs-src/src/components/TestChat.vue, src/components/DynamicScroller.vue
extracted from #248 
fix https://github.com/Akryum/vue-virtual-scroller/pull/248#issuecomment-506867517
The original issue that #248 tried to solve is already solved on the current master branch but there still is an issue when upper items are loaded.
In the case the current scroll position is bottom and scrolling up, the upper items will be loaded and their size will be set lazily. When the size is set to concrete value, the remaining items will be pushed for bottom, then scroll looks jumpy.
To avoid this, I'm comparing prev and next height of items and add the offset to scrollTop.
=> fix: avoid jumping scroll position when upper item size is calculated

docs-src/src/components/RecycleScrollerDemo.vue, src/components/RecycleScroller.vue
Fix #307
It has special logic when `scrollToItem` is called to take into account items that are before actual scroller.
=> fix: scrollToItem works with pageMode

packages/vue-virtual-scroller/src/components/RecycleScroller.vue
**Description**
```
Fix RecycleScroller scrollToItem method when itemSize is not null.  
Scroll position is wrong because gridItems is undefined.
```
**Reproduction**
[Demo site](https://vue-virtual-scroller-demo.netlify.app/recycle)
```
1. unchecked 'variable height'
2. click 'Scroll To:' button
3. list scroll to 'item 0' (not 'item 100')
```
=> fix(RecycleScroller): gridItems is undefined when scrollToItem, fix #773

packages/vue-virtual-scroller/README.md, packages/vue-virtual-scroller/src/components/RecycleScroller.vue
updateVisibleItems needs to get the value of scrollTop, which can be expensive because of layout calculations. Further, checking the view at 60fps can be overkill, especially if you have a well-sized buffer. Setting updateInterval to a small value such as 100ms drastically reduces CPU usage.
Signed-off-by: Varun Patil <varunpatil@ucla.edu>
Chrome CPU profile comparison under identical conditions (and no visible change to user experience).
=> feat: allow throttling update calls

packages/vue-virtual-scroller/src/components/RecycleScroller.vue
This commit rewrites the view (re-)assignment logic in a way that is shorter
and therefore easier to read through. The performance is generally on par with
the old implementation. It also fixes bugs in the old logic where:
- The item itself getting used as the keyField instead of the index.
- Sometimes a view could get stuck in a corrupted state where its key doesn't
match what the index or item indicates.
These bugs were rather hard to reason about in the old logic due to the
redundant code path it had (which weakened the invariants). The new logic
unifies paths for simplicity, while keeping the time complexity aspect roughly
the same.
I've done some brief tests on this using my own app and it has been working fine, even better because there were some annoying bugs before as described …
=> fix: Rewrite view (re-)assignment logic

packages/vue-virtual-scroller/src/components/DynamicScroller.vue
Currently, when using `<DynamicScroller>` it always render `<slot name="before" />` and `<slot name="after" />`. Maybe we can avoid rendering these two nodes when they are not actually used.
=> fix: avoid rendering when slot is unused

packages/vue-virtual-scroller/src/components/RecycleScroller.vue
It looks like the code for view sorting was accidentally changed when creating the Vue3 version. Reverting this changes ensures the functionality works correctly.
=> fix: view sorting in next

packages/vue-virtual-scroller/src/components/ItemView.vue, packages/vue-virtual-scroller/src/components/RecycleScroller.vue
When rendering a slot, Vue will act as if the slot content was expanded
in-line at the `<slot>`'s place.
Having the slots in a v-for therefore can trigger too much rerender for the
slot content, and was generally bad for performance.
Wrapping them in a component should provide some performance improvements as
well as solving the hover update overhead.
=> fix(RecycleScroller): Introduce an item wrapper to reduce re-render 

packages/vue-virtual-scroller/src/components/DynamicScrollerItem.vue
This is a PR for solution proposed by @NguyenHoan2201 in the issue below:
[#821 -  iphone safari scroll up flicker](https://github.com/Akryum/vue-virtual-scroller/issues/821)
I've tested the fix and it works.
=> fix: flicker issue in ios when scrolling up
